"""
Migration v2: Add inbound staging tables + payload columns to ticket/ticket_item.

Run: python scripts/migrate_v2_staging.py
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.append(str(ROOT))

from app.db.session import engine


SQL = """
-- 1. Add source_header_payload to ticket if not exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'competitor_ticket' AND table_name = 'ticket' AND column_name = 'source_header_payload'
    ) THEN
        ALTER TABLE competitor_ticket.ticket ADD COLUMN source_header_payload text;
    END IF;
END $$;

-- 2. Add source_item_payload to ticket_item if not exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'competitor_ticket' AND table_name = 'ticket_item' AND column_name = 'source_item_payload'
    ) THEN
        ALTER TABLE competitor_ticket.ticket_item ADD COLUMN source_item_payload text;
    END IF;
END $$;

-- 3. Create inbound_ticket_header if not exists
CREATE TABLE IF NOT EXISTS competitor_ticket.inbound_ticket_header (
    inbound_header_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                  BIGINT NOT NULL REFERENCES competitor_ticket.integration_batch(batch_id) ON UPDATE RESTRICT ON DELETE CASCADE,
    source_ticket_code        VARCHAR(30) NOT NULL,
    source_business_code      VARCHAR(30) NOT NULL,
    source_store_code         VARCHAR(30) NOT NULL,
    source_ticket_date        DATE NOT NULL,
    source_ticket_key         VARCHAR(120) NOT NULL,
    source_status_code        VARCHAR(10),
    payload_json              TEXT NOT NULL,
    is_processed              BOOLEAN NOT NULL DEFAULT FALSE,
    processed_at              TIMESTAMPTZ,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Create inbound_ticket_item if not exists
CREATE TABLE IF NOT EXISTS competitor_ticket.inbound_ticket_item (
    inbound_item_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                  BIGINT NOT NULL REFERENCES competitor_ticket.integration_batch(batch_id) ON UPDATE RESTRICT ON DELETE CASCADE,
    source_ticket_code        VARCHAR(30) NOT NULL,
    source_business_code      VARCHAR(30) NOT NULL,
    source_store_code         VARCHAR(30) NOT NULL,
    source_ticket_date        DATE NOT NULL,
    source_ticket_key         VARCHAR(120) NOT NULL,
    source_item_sequence      INTEGER NOT NULL,
    product_code              VARCHAR(50),
    product_description       VARCHAR(255),
    quantity                  NUMERIC(18,4),
    unit_price                NUMERIC(18,4),
    line_amount               NUMERIC(18,4),
    payload_json              TEXT NOT NULL,
    is_processed              BOOLEAN NOT NULL DEFAULT FALSE,
    processed_at              TIMESTAMPTZ,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Create inbound_ticket_store if not exists
CREATE TABLE IF NOT EXISTS competitor_ticket.inbound_ticket_store (
    inbound_store_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                  BIGINT NOT NULL REFERENCES competitor_ticket.integration_batch(batch_id) ON UPDATE RESTRICT ON DELETE CASCADE,
    source_ticket_code        VARCHAR(30) NOT NULL,
    source_business_code      VARCHAR(30) NOT NULL,
    source_store_code         VARCHAR(30) NOT NULL,
    source_ticket_date        DATE NOT NULL,
    source_ticket_key         VARCHAR(120) NOT NULL,
    applies_to_store_code     VARCHAR(30) NOT NULL,
    payload_json              TEXT NOT NULL,
    is_processed              BOOLEAN NOT NULL DEFAULT FALSE,
    processed_at              TIMESTAMPTZ,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Create unique indexes/constraints
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_inbound_ticket_header_batch_key') THEN
        ALTER TABLE competitor_ticket.inbound_ticket_header ADD CONSTRAINT uq_inbound_ticket_header_batch_key UNIQUE (batch_id, source_ticket_key);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_inbound_ticket_item_batch_key_seq') THEN
        ALTER TABLE competitor_ticket.inbound_ticket_item ADD CONSTRAINT uq_inbound_ticket_item_batch_key_seq UNIQUE (batch_id, source_ticket_key, source_item_sequence);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_inbound_ticket_store_batch_key_store') THEN
        ALTER TABLE competitor_ticket.inbound_ticket_store ADD CONSTRAINT uq_inbound_ticket_store_batch_key_store UNIQUE (batch_id, source_ticket_key, applies_to_store_code);
    END IF;
END $$;

-- 7. Create indexes for staging tables
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_header_batch ON competitor_ticket.inbound_ticket_header(batch_id);
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_header_source_ticket_key ON competitor_ticket.inbound_ticket_header(source_ticket_key);
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_header_is_processed ON competitor_ticket.inbound_ticket_header(is_processed);
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_item_batch ON competitor_ticket.inbound_ticket_item(batch_id);
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_item_source_ticket_key ON competitor_ticket.inbound_ticket_item(source_ticket_key);
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_item_is_processed ON competitor_ticket.inbound_ticket_item(is_processed);
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_store_batch ON competitor_ticket.inbound_ticket_store(batch_id);
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_store_source_ticket_key ON competitor_ticket.inbound_ticket_store(source_ticket_key);
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_store_store_code ON competitor_ticket.inbound_ticket_store(applies_to_store_code);
CREATE INDEX IF NOT EXISTS idx_inbound_ticket_store_is_processed ON competitor_ticket.inbound_ticket_store(is_processed);
"""


def main():
    print("Running migration v2 (staging tables + payload columns)...")
    with engine.begin() as conn:
        conn.exec_driver_sql(SQL)
    print("Migration v2 completed successfully.")

if __name__ == '__main__':
    main()
